DROP VIEW IF EXISTS V_SESSION_WITH_CONNECTIONS_DETAILS;

CREATE VIEW V_SESSION_WITH_CONNECTIONS_DETAILS AS
SELECT
    S.FOLDER_NAME,
    S.WORKFLOW_NAME,
    S.WORKFLOW_ID,
    S.SESSION_NAME,
    S.CMD_TASK_NAME,
    S.CMD_NAME,
    S.SCRIPT_TYPE,
    C.CONNECTION_NAME,
    C.CONNECTION_TYPE,
    C.CONNECTION_STRING,
    C.DATABASE_NAME,
    C.HOST_NAME,
    C.PORT_NUMBER,
    C.SERVICE_NAME,
    S.INFORMATICA_SERVER,
    S.INFORMATICA_USER,
    CASE
        WHEN C.CONNECTION_NAME IS NULL THEN 1
        ELSE 0
    END AS MISSING_CONNECTION
FROM
    INFORMATICA_SESSIONS_CONNECTIONS S
LEFT JOIN
    INFORMATICA_CONNECTIONS_DETAILS C
ON
    C.INFORMATICA_SERVER = S.INFORMATICA_SERVER
AND
    C.INFORMATICA_USER = S.INFORMATICA_USER
AND
    C.CONNECTION_NAME = S.CONNECTION_NAME;

DROP VIEW IF EXISTS V_WORKFLOWS_ROOT;
CREATE VIEW V_WORKFLOWS_ROOT AS  SELECT DISTINCT FOLDER_NAME,WORKFLOW_ID,SESSION_WF_NAME,WORKFLOW_ID,
 "PATH",INFORMATICA_SERVER,INFORMATICA_USER FROM INFORMATICA_HIERARCHY_STRUCTURE WHERE WORKFLOW_ID IS NOT NULL AND SESSION_ID IS NULL;

DROP VIEW IF EXISTS V_WF_HIERARCHY_EXPLORER;

CREATE VIEW V_WF_HIERARCHY_EXPLORER AS
SELECT DISTINCT
    H.INFORMATICA_USER,
    H.FOLDER_NAME,
    H."PATH",
    H.HIERARCHY_STRUCTURE,
    H.WORKFLOW_ID,
    V.SESSION_NAME,
    V.CMD_TASK_NAME,
    V.CMD_NAME,
    V.SCRIPT_TYPE,
    V.CONNECTION_NAME,
    V.CONNECTION_TYPE,
    V.HOST_NAME,
    V.DATABASE_NAME ,
    V.PORT_NUMBER,
    V.SERVICE_NAME ,
    V.MISSING_CONNECTION
FROM
    INFORMATICA_HIERARCHY_STRUCTURE H
LEFT JOIN
    V_SESSION_WITH_CONNECTIONS_DETAILS V
ON
    (H.SESSION_WF_NAME = V.SESSION_NAME  )
    AND H.FOLDER_NAME = V.FOLDER_NAME
    AND H.INFORMATICA_USER = V.INFORMATICA_USER
ORDER BY
    H.INFORMATICA_USER,
    H.FOLDER_NAME,
    H.HIERARCHY_STRUCTURE DESC;