DROP TABLE IF EXISTS INFORMATICA_SESSIONS_CONNECTIONS;

-- INFORMATICA_SESSIONS_CONNECTIONS definition

--- NPCI , Centos
-- all scripts and commands
--
--SELECT
--  F.SUBJECT_AREA AS FOLDER_NAME,
--  W.TASK_NAME AS WORKFLOW_NAME,
--    T.RU_PARENT_ID as WORKFLOW_ID,
--  A.TASK_NAME AS SESSION_NAME,
--    '' as CONNECTION_TYPE,
--  '' as CONNECTION_NAME,
--  '' as DIR_NAME,
--  '' as FILE_NAME,
--  CMD.VAL_NAME AS CMD_TASK_NAME,
--  CMD.PM_VALUE AS CMD_NAME,
--  CASE
--    WHEN CMD.PM_VALUE LIKE '%.sh%' THEN 'sh'
--    WHEN CMD.PM_VALUE LIKE '%.py%' THEN 'python'
--    ELSE NULL
--  END AS SCRIPT_TYPE,
--      SYS_CONTEXT('USERENV', 'DB_NAME') AS informatica_server,
--  SYS_CONTEXT('USERENV', 'SESSION_USER') AS informatica_user,
--  TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI:SS') AS CREATED_DATE
--FROM
--  INFO_REP_PROD.OPB_TASK T
--LEFT OUTER JOIN INFO_REP_PROD.OPB_TASK_VAL_LIST CMD
--  ON T.TASK_ID = CMD.TASK_ID
--LEFT OUTER JOIN INFO_REP_PROD.REP_ALL_TASKS A
--  ON A.TASK_ID = T.TASK_ID,
--  INFO_REP_PROD.OPB_TASK W,
--  INFO_REP_PROD.REP_SUBJECT F
--WHERE
----  F.SUBJECT_AREA IN ('PCI','PCI_TRANSFORMER','Shared_Objects')
--   T.SUBJECT_ID = F.SUBJECT_ID
--  AND T.RU_PARENT_ID = W.TASK_ID and
----  A.TASK_TYPE_NAME ='Command' and
--  CMD.VAL_NAME is not null  order by 1,2,3,4,5 ;

--- PCI , Rhel
-- all scripts and commands
--
--SELECT
--  F.SUBJECT_AREA AS FOLDER_NAME,
--  W.TASK_NAME AS WORKFLOW_NAME,
--  T.RU_PARENT_ID as WORKFLOW_ID,
--  A.TASK_NAME AS SESSION_NAME,
--    '' as CONNECTION_TYPE,
--  '' as CONNECTION_NAME,
--  '' as DIR_NAME,
--  '' as FILE_NAME,
--  CMD.VAL_NAME AS CMD_TASK_NAME,
--  CMD.PM_VALUE AS CMD_NAME,
--  CASE
--    WHEN CMD.PM_VALUE LIKE '%.sh%' THEN 'sh'
--    WHEN CMD.PM_VALUE LIKE '%.py%' THEN 'python'
--    ELSE NULL
--  END AS SCRIPT_TYPE,
--      SYS_CONTEXT('USERENV', 'DB_NAME') AS informatica_server,
--  SYS_CONTEXT('USERENV', 'SESSION_USER') AS informatica_user,
--  TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI:SS') AS CREATED_DATE
--FROM
--  OPB_TASK T
--LEFT OUTER JOIN OPB_TASK_VAL_LIST CMD
--  ON T.TASK_ID = CMD.TASK_ID
--LEFT OUTER JOIN REP_ALL_TASKS A
--  ON A.TASK_ID = T.TASK_ID,
--  OPB_TASK W,
--  REP_SUBJECT F
--WHERE
----  F.SUBJECT_AREA IN ('PCI','PCI_TRANSFORMER','Shared_Objects')
--   T.SUBJECT_ID = F.SUBJECT_ID
--  AND T.RU_PARENT_ID = W.TASK_ID and
----  A.TASK_TYPE_NAME ='Command' and
--  CMD.VAL_NAME is not null  order by 1,2,3,4,5 ;



-- PCI , RHEL -  generate all sessions

--select SUBJECT_AREA as FOLDER_NAME,
--WORKFLOW_ID as WORKFLOW_ID,
--SESSION_INSTANCE_NAME as SESSION_NAME,
--''  as CONNECTION_TYPE,
--CONNECTION_NAME as CONNECTION_NAME,
--'' as DIR_NAME,
--''  as FILE_NAME ,
--'' as CMD_TASK_NAME,
--'' as CMD_NAME,
--'' as SCRIPT_TYPE,
-- SYS_CONTEXT('USERENV', 'DB_NAME') AS informatica_server,
-- SYS_CONTEXT('USERENV', 'SESSION_USER') AS informatica_user,
-- TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI:SS') AS created_date ,
-- '' as UPDATED_DATE
--  from REP_SESSION_INSTANCES  order by SUBJECT_AREA,WORKFLOW_ID;



-- NPCI , RHel - all sessions
--select SUBJECT_AREA as FOLDER_NAME,
--WORKFLOW_ID as WORKFLOW_ID,
--SESSION_INSTANCE_NAME as SESSION_NAME,
--''  as CONNECTION_TYPE,
--CONNECTION_NAME as CONNECTION_NAME,
--'' as DIR_NAME,
--''  as FILE_NAME ,
--'' as CMD_TASK_NAME,
--'' as CMD_NAME,
--'' as SCRIPT_TYPE,
-- SYS_CONTEXT('USERENV', 'DB_NAME') AS informatica_server,
-- SYS_CONTEXT('USERENV', 'SESSION_USER') AS informatica_user,
-- TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI:SS') AS created_date ,
-- '' as UPDATED_DATE
--  from INFO_REP_PROD.REP_SESSION_INSTANCES  order by SUBJECT_AREA,WORKFLOW_ID;


CREATE TABLE INFORMATICA_SESSIONS_CONNECTIONS (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    FOLDER_NAME VARCHAR2(50),
    WORKFLOW_NAME VARCHAR2(100),
        WORKFLOW_ID VARCHAR2(20),
    SESSION_NAME VARCHAR2(200),
    CONNECTION_TYPE VARCHAR2(50),
    CONNECTION_NAME VARCHAR2(50),
    DIR_NAME VARCHAR2(250),
    FILE_NAME VARCHAR2(199),
    CMD_TASK_NAME varchar2(100),
    CMD_NAME varchar2(400),
    SCRIPT_TYPE varchar2(50),
    INFORMATICA_SERVER varchar2(50),
    INFORMATICA_USER varchar2(50),
     CREATED_DATE DATE,
     UPDATED_DATE DATE
  );
