DROP TABLE IF EXISTS SCRIPTS_DETAILS;

CREATE TABLE SCRIPTS_DETAILS (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    INFOMATICA_USER    VARCHAR2(50),
    WORKFLOW           VARCHAR2(100),
    FULLPATH           VARCHAR2(500),
    PARAMETER_FILE     VARCHAR2(500),
    CONNECTIONS        VARCHAR2(500),
    USE_TNS            CHAR(1),
    COMMENT            VARCHAR2(1000) ,
    CREATED_DATE DATE,
    UPDATED_DATE DATE);
